name: Run Trading Bot

on:
  schedule:
    - cron: '*/5 * * * *' # Jalan tiap 5 menit
  workflow_dispatch:      # Tombol run manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # ðŸ‘‡ TAMBAHKAN BAGIAN INI ðŸ‘‡
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install ccxt requests numpy pandas

      - name: Run Bot
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          ORION_COOKIES_JSON: ${{ secrets.ORION_COOKIES_JSON }}
        run: python bot_cloud.py
